FROM alpine:3.20.6 AS builder

ARG SOFTHSM_V2_VERSION=2.6.1

RUN apk --update add \
    git \
    openssl-dev \
    automake autoconf libtool pkgconfig \
    alpine-sdk

RUN git clone -b ${SOFTHSM_V2_VERSION} https://github.com/opendnssec/SoftHSMv2.git /tmp/SoftHSMv2/
WORKDIR /tmp/SoftHSMv2/

RUN sh ./autogen.sh \
    && ./configure \
    && make \
    && make install

FROM golang:1.23.9-alpine3.20

RUN apk --no-cache add libstdc++ openssl musl opensc build-base

# gcc is installed through the build-base package.
ENV CGO_ENABLED=1

RUN apk --no-cache add libjpeg qpdf # Install the QPDF command which is used in the tests.

COPY --from=builder /usr/local/lib/softhsm/ /usr/local/lib/softhsm/
COPY --from=builder /usr/local/bin/softhsm* /usr/local/bin/
COPY --from=builder /etc/softhsm* /etc/
COPY --from=builder /var/lib/softhsm/ /var/lib/softhsm/
# Manual (man) documents not copied over.

VOLUME /var/lib/softhsm/

CMD softhsm2-util --help